version: '3.9'

volumes:
  postgres_volume:

services:

  db:
    container_name: postgres_db_cont
    image: postgres:14.3-alpine3.15
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U alexander -d orders"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    volumes:
      - postgres_volume:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin_cont
    image: dpage/pgadmin4:5.7
    env_file:
      - .env
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
