# Generated by Django 2.2.16 on 2023-04-30 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0002_confirmemailtoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confirmemailtoken',
            options={'verbose_name': 'Токен подтверждения email', 'verbose_name_plural': 'Токены подтверждения email'},
        ),
    ]
