# Generated by Django 4.2.1 on 2023-05-22 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0004_alter_user_first_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confirmemailtoken',
            options={'managed': True, 'verbose_name': 'Токен подтверждения email', 'verbose_name_plural': 'Токены подтверждения email'},
        ),
    ]
