# Generated by Django 4.2.1 on 2023-05-22 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0005_alter_confirmemailtoken_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confirmemailtoken',
            options={'verbose_name': 'Токен подтверждения email', 'verbose_name_plural': 'Токены подтверждения email'},
        ),
    ]
